name: Deploy to Deta
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: BogDAAAMN/deta-deploy-action@v1.0.0
        with:
          deta-access-token: ${{ secrets.DETA_TOKEN }}
          deta-name: 'micro-name' #Deta Micro name https://docs.deta.sh/docs/cli/commands/#deta-clone
          deta-project: 'project-name' #Deta project name https://docs.deta.sh/docs/cli/commands/#deta-clone
